service {
  vgroupMapping.railway-ticket-tx-group = "default"
  default.grouplist = "127.0.0.1:8091"
  enableDegrade = false
  disableGlobalTransaction = false
}

client {
  application.id = train-service
  transaction.service.group = railway-ticket-tx-group
}

store {
  mode = "file"
  file {
    dir = "sessionStore"
  }
}
