service {
  vgroupMapping.railway-ticket-tx-group = "default"
  default.grouplist = "seata-server:8091"
  enableDegrade = false
  disableGlobalTransaction = false
}

store {
  mode = "db"
  db {
    datasource = "mysql"
    dbType = "mysql"
    driverClassName = "com.mysql.cj.jdbc.Driver"
    url = "jdbc:mysql://mysql-seata:3306/seata?useSSL=false&serverTimezone=Asia/Shanghai"
    user = "root"
    password = "052834"
    minConn = 5
    maxConn = 100
    globalTable = "global_table"
    branchTable = "branch_table"
    lockTable = "lock_table"
    queryLimit = 100
    maxWait = 5000
  }
}
